
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
          map-underscore-to-camel-case: true
          default-fetch-size: 50
          default-statement-timeout: 10
          auto-mapping-unknown-column-behavior: WARNING
  type-aliases-package: com.cristik.boot.application.dao
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456